# This workflow will create a PR if there are pushes to the 
# actions/version-bump branch, which release will automatically
# create by incrementing VERSION (see release.yml)

name: Create Version Bump PR 

on:
  push:
    branches: [ actions/version-bump ]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create Pull Request 
      uses: repo-sync/pull-request@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        destination_branch: "master"
        pr_title: "Bumping VERSION file due to recent release"
        pr_body: "*Automated PR*: This should update the candidate version. Please delete source branch upon merge"
        pr_reviewer: "schahal"
        pr_assignee: "schahal"
